#!/bin/bash
# This script automates file transfer from a client to a server
# It uses the $# variable to check the number of command-line arguments
# For this script we expect 4 arguments   
# arg1: path to the file to be transferred "$1"
# arg2: IP of the server we want to transfer the file to "$2"
# arg3: username scp connects with "$3"
# arg4: path to the SSH private key that scp uses "$4"
# We will display an error message if less than 3 args are provided
# scp must transfer the file to the user home directory ~/
# Strict host key checking must be disabled when using scp

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
    # Transfers the file to the remote server without specifying an SSH key
    scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
    # Transfers the file to the remote server using the specified SSH key
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
