#!/usr/bin/env bash
# This script once executed will install Nginx web server 

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
