#!/usr/bin/env bash
# Configuring the headers
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
