#!/usr/bin/env bash
# debugging nginx port 80
# Step 1: delete the existing ../sites-enabled/default and replace it with a copy of
# ../sites-available/default. This is done by creating a symbolic link. 
# Step2: The -s flag creates a symbolic link, -f deletes and replaces the existing file

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
