#!/usr/bin/env bash
# debugging nginx
# the init service must says  nginx is not running

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
