#!/usr/bin/env bash
# Script configures an Ubuntu server by:
# 	resolving localhost to 127.0.0.2
# 	resolving facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
